version: "3.7"

services:
    auth_server:
        container_name: auth_server
        build: .
        volumes:
            - .:/app
        env_file:
            - ./.env
        environment:
            - PORT=8080
            - HOSTNAME=auth_server
            - DB_USERNAME="dbuser"
            - DB_PASSWORD="dbpass"               
    
    postgis:
        image: kartoza/postgis
        restart: always
        ports: 25432:5432
        volumes: pg_data:/var/lib/postgresql
        environment: 
            - POSTGRES_USER="dbuser" 
            - POSTGRES_PASS="dbpass"
            - POSTGRES_DBNAME="postgres"

    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
        - auth_server