version: "3.7"

services:
    auth_server:
        container_name: auth_server
        build: .
        volumes:
            - .:/app
        env_file:
            - ./.env
        environment:
            - PORT=8080

    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
        - auth_server